from __future__ import annotations

import json
import re
import urllib.request
from pathlib import Path
from html import unescape

URL = "https://go313.ru/"
OUT = Path("debug/tilda-projects.json")
SOURCE = Path("debug/tilda-source.html")

request = urllib.request.Request(URL, headers={"User-Agent": "Mozilla/5.0"})
with urllib.request.urlopen(request, timeout=40) as response:
    html = response.read().decode("utf-8", errors="replace")

SOURCE.parent.mkdir(parents=True, exist_ok=True)
SOURCE.write_text(html, encoding="utf-8")

# Keep every Tilda CDN image URL with nearby HTML context. This catches images
# stored in lazy-loading attributes, inline data arrays, and popup galleries.
url_pattern = re.compile(r"https://static\.tildacdn\.com/[^\"'<>\\s]+", re.I)
urls: list[dict[str, object]] = []
seen: set[str] = set()
for match in url_pattern.finditer(html):
    url = unescape(match.group(0)).replace("\\/", "/")
    if url in seen:
        continue
    seen.add(url)
    start = max(0, match.start() - 500)
    end = min(len(html), match.end() + 500)
    context = re.sub(r"\s+", " ", html[start:end])
    urls.append({"url": url, "position": match.start(), "context": context})

# Find links that open project popups and locate matching popup blocks.
popup_links: list[dict[str, object]] = []
for match in re.finditer(r"<a\b[^>]*href=[\"'](#[^\"']*popup[^\"']*)[\"'][^>]*>(.*?)</a>", html, re.I | re.S):
    href = unescape(match.group(1))
    text = re.sub(r"<[^>]+>", " ", match.group(2))
    text = re.sub(r"\s+", " ", unescape(text)).strip()
    popup_links.append({"href": href, "text": text, "position": match.start()})

# Also catch Tilda's #popup:name syntax in arbitrary attributes/scripts.
popup_names = sorted(set(re.findall(r"#popup:[A-Za-zА-Яа-я0-9_\-]+", html)))

popups: list[dict[str, object]] = []
for name in popup_names:
    positions = [m.start() for m in re.finditer(re.escape(name), html)]
    records = []
    for position in positions:
        start = max(0, position - 1200)
        end = min(len(html), position + 18000)
        block = html[start:end]
        block_urls = []
        for url_match in url_pattern.finditer(block):
            value = unescape(url_match.group(0)).replace("\\/", "/")
            if value not in block_urls:
                block_urls.append(value)
        records.append({
            "position": position,
            "context": re.sub(r"\s+", " ", block[:2400]),
            "urls": block_urls,
        })
    popups.append({"name": name, "occurrences": records})

# Gather Tilda record IDs with image URLs. Popup records often group the exact
# project gallery images even when the markup is generated by JavaScript.
records: list[dict[str, object]] = []
for match in re.finditer(r"<div[^>]+id=[\"']rec(\d+)[\"'][^>]*>", html, re.I):
    rec_id = match.group(1)
    start = match.start()
    next_match = re.search(r"<div[^>]+id=[\"']rec\d+[\"'][^>]*>", html[match.end():], re.I)
    end = match.end() + next_match.start() if next_match else min(len(html), start + 50000)
    block = html[start:end]
    block_urls = []
    for url_match in url_pattern.finditer(block):
        value = unescape(url_match.group(0)).replace("\\/", "/")
        if value not in block_urls:
            block_urls.append(value)
    if block_urls or "popup" in block.lower():
        plain = re.sub(r"<[^>]+>", " ", block[:4000])
        plain = re.sub(r"\s+", " ", unescape(plain)).strip()
        records.append({"record_id": rec_id, "urls": block_urls, "text": plain[:800]})

OUT.write_text(
    json.dumps(
        {
            "source_url": URL,
            "total_unique_cdn_urls": len(urls),
            "popup_links": popup_links,
            "popups": popups,
            "records": records,
            "all_urls": urls,
        },
        ensure_ascii=False,
        indent=2,
    ),
    encoding="utf-8",
)
print(f"Saved {OUT} with {len(urls)} unique URLs and {len(popups)} popup names")
